version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql

  # PHP FPM Service
  php:
    image: wodby/php:latest
    volumes:
      - ./source:/var/www/html
    depends_on:
      - mariadb

  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - "88:80"
    links:
      - php
    volumes:
      - ./source:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php

volumes:
  db_data:
